[package]
name = "fluence_keypairs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fluence-keypair = "0.10.3"
bs58 = "0.5.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
